baseURL = 'https://RICOMP4.github.io/'
languageCode = 'fr-fr'
title = 'À propos de moi'
theme = 'ananke'

[params]
  text_color = "black-80"
  background_color_class = "bg-white"
  cover_color = "blue"
  custom_css = ["css/custom.css"]
